# Generated by Django 3.0.5 on 2020-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_api', '0002_documentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentanswer',
            name='raw_answer',
            field=models.TextField(null=True),
        ),
    ]
